"""empty message

Revision ID: 296cb3057755
Revises: f18d29cc815c
Create Date: 2017-02-25 19:20:55.754975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296cb3057755'
down_revision = 'f18d29cc815c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail', 'name')
    # ### end Alembic commands ###
