"""empty message

Revision ID: 49c3959e4949
Revises: fc6b18f46d3c
Create Date: 2017-02-27 15:12:24.922313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c3959e4949'
down_revision = 'fc6b18f46d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tomcat_project', sa.Column('code_dir', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tomcat_project', 'code_dir')
    # ### end Alembic commands ###
