"""empty message

Revision ID: 59d998ba1320
Revises: 
Create Date: 2017-02-25 11:14:31.793039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d998ba1320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('mail', sa.Column('role', sa.String(length=10), nullable=True))
    op.alter_column('mail', 'status', existing_type=mysql.VARCHAR(length=20))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mail', 'role')
    # ### end Alembic commands ###

