"""empty message

Revision ID: 7d526607dc87
Revises: d03d2a91abdd
Create Date: 2017-02-25 13:34:24.802631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d526607dc87'
down_revision = 'd03d2a91abdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail', 'status',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation=u'utf8_bin', length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
