"""empty message

Revision ID: 91c69819462f
Revises: b669f39172de
Create Date: 2017-02-26 00:51:38.921129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c69819462f'
down_revision = 'b669f39172de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tomcat_project', sa.Column('product', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'tomcat_project', ['product'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tomcat_project', type_='unique')
    op.drop_column('tomcat_project', 'product')
    # ### end Alembic commands ###
