"""empty message

Revision ID: a4d3152535f7
Revises: efca99bb4948
Create Date: 2017-02-25 16:55:17.170335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d3152535f7'
down_revision = 'efca99bb4948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_server', sa.Column('info', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_server', 'info')
    # ### end Alembic commands ###
