"""empty message

Revision ID: b669f39172de
Revises: d35a2a92422b
Create Date: 2017-02-26 00:47:31.624530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b669f39172de'
down_revision = 'd35a2a92422b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tomcat_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=32), nullable=True),
    sa.Column('tomcat', sa.String(length=64), nullable=True),
    sa.Column('main_port', sa.String(length=10), nullable=True),
    sa.Column('jdk', sa.String(length=10), nullable=True),
    sa.Column('script', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tomcat_project')
    # ### end Alembic commands ###
