"""empty message

Revision ID: d35a2a92422b
Revises: 296cb3057755
Create Date: 2017-02-25 21:30:03.805265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35a2a92422b'
down_revision = '296cb3057755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tomcat_url', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tomcat_url', type_='unique')
    # ### end Alembic commands ###
