"""empty message

Revision ID: f18d29cc815c
Revises: a4d3152535f7
Create Date: 2017-02-25 17:25:32.833891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f18d29cc815c'
down_revision = 'a4d3152535f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitor_server', 'url',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitor_server', 'url',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation=u'utf8_bin', length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
