"""empty message

Revision ID: fc6b18f46d3c
Revises: 91c69819462f
Create Date: 2017-02-26 00:52:52.006469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6b18f46d3c'
down_revision = '91c69819462f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product', table_name='tomcat_project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product', 'tomcat_project', ['product'], unique=True)
    # ### end Alembic commands ###
